version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: # this contains the configuation required by the app
      - .env
  web:
    build: .
    command: dotnet SSGDistributer.exe
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5001:80"
    depends_on:
      - db